version: "3.4"

services:
  chat-tts-api:
    image: chat-tts-api-cpu:latest
    container_name: chat-tts-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TTS_DEVICE=cpu
      - HF_ENDPOINT=https://hf-mirror.com
      - HF_HOME=/app/huggingface
    ports:
      - "11400:9000"
